# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94493e57ec8f0e1f844a7a1d9da30619faa437c5ae6cad1f1920306f4d0a27674caff0883710915a54fa6d52f93e595145f34fce7a04829f2f11312a8ca55a8d

test:
  secret_key_base: fa89ab7dd5bfb67950e7e5c6d3d0daf519ebc00cab0ba786e16e77f78d80214fd0b7f354a44ec895058681f6bbfe15feafd5e448b695211a281bcb3a12bfcd76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
